import { useMemo } from 'react';

import type { MessageKey } from '../../i18n/index.js';
import { usePlatform } from '../context/PlatformContext.js';
import { INSTITUTION_ROUTES } from '../platform/institutionalRoutes.js';

const ROUTE_STEP_IDS = ['os', 'catalog', 'pilot', 'close'] as const;
const COMPARE_DIM_IDS = ['efficiency', 'results', 'security', 'citizens'] as const;
const PIPELINE_STEP_IDS = ['received', 'validated', 'decided', 'committed', 'published'] as const;

const PROGRAM_KEYS: Record<string, MessageKey> = {
  ven: 'demo.program.ven',
  col: 'demo.program.col',
  usa: 'demo.program.usa',
  sbx: 'demo.program.gen',
  gen: 'demo.program.gen',
};

export function useLandingCopy() {
  const { t, sovereign } = usePlatform();

  return useMemo(() => {
    const programKey = PROGRAM_KEYS[sovereign.iso.toLowerCase()] ?? 'demo.program.gen';

    return {
      HERO_SCREEN_LABELS: [
        t('hero.screen.demo'),
        t('hero.screen.route'),
        t('hero.screen.pilot'),
      ] as const,
      HERO_CINEMATIC_TITLE: t('hero.cinematic.title'),
      HERO_CINEMATIC_TAGLINE: t('hero.cinematic.tagline'),
      HERO_CINEMATIC_SUBLINE: t('hero.cinematic.subline'),
      HERO_NOT_LLM: t('hero.cinematic.notLlm'),
      HERO_GATES_ARIA: t('hero.gates.aria'),
      HERO_GATES: [
        {
          id: 'explore' as const,
          label: t('hero.gates.explore.label'),
          hint: t('hero.gates.explore.hint'),
          path: '/modelos',
        },
        {
          id: 'deploy' as const,
          label: t('hero.gates.deploy.label'),
          hint: t('hero.gates.deploy.hint'),
          path: INSTITUTION_ROUTES.register,
        },
        {
          id: 'discover' as const,
          label: t('hero.gates.discover.label'),
          hint: t('hero.gates.discover.hint'),
          path: '/#autoridad',
        },
      ],
      HERO_SELL_LEAD: t('hero.sell.lead'),
      HERO_SELL_POINTS: [t('hero.sell.point1'), t('hero.sell.point2'), t('hero.sell.point3')] as const,
      HERO_DIAGRAM_EYEBROW: t('hero.diagram.eyebrow'),
      HERO_DIAGRAM_PATH: t('hero.diagram.path'),
      HERO_DIAGRAM_HUB: t('hero.diagram.hub'),
      HERO_DIAGRAM_HUB_SUB: t('hero.diagram.hubSub'),
      HERO_DIAGRAM_NODES: {
        ingest: t('hero.diagram.node.ingest'),
        multisig: t('hero.diagram.node.multisig'),
        escrow: t('hero.diagram.node.escrow'),
        sentinel: t('hero.diagram.node.sentinel'),
        ledger: t('hero.diagram.node.ledger'),
        publish: t('hero.diagram.node.publish'),
      },
      HERO_CINEMATIC_LIVE_CAPTION: t('hero.cinematic.liveCaption', {
        jurisdiction: sovereign.jurisdictionCode,
      }),
      HERO_CTA_MICRO: t('hero.cinematic.micro'),
      HERO_TRUST_LINE: t('hero.cinematic.trust'),
      HERO_CTA_PRIMARY: { label: t('hero.cta.primary'), path: INSTITUTION_ROUTES.register },
      HERO_CTA_SECONDARY: {
        label: t('hero.cta.secondary'),
        path: '/desarrolladores',
        external: false,
      },
      HERO_CTA_DEV: t('hero.cta.dev'),
      HERO_CTA_GITHUB_LABEL: t('hero.cta.github'),
      HERO_CTA_GITHUB: 'https://github.com/armadaai-sas/Armada-VZLA',
      HERO_STAGE_KICKER: t('hero.stage.kicker'),
      LANDING_AUTHORITY_KICKER: t('landing.authority.kicker'),
      LANDING_AUTHORITY_TITLE: t('landing.authority.title'),
      LANDING_AUTHORITY_LEAD: t('landing.authority.lead'),
      LANDING_AUTHORITY_COPILOT_TITLE: t('landing.authority.copilot.title'),
      LANDING_AUTHORITY_COPILOT_BODY: t('landing.authority.copilot.body'),
      LANDING_AUTHORITY_OS_TITLE: t('landing.authority.os.title'),
      LANDING_AUTHORITY_OS_BODY: t('landing.authority.os.body'),
      LANDING_AUTHORITY_FOOT: t('landing.authority.foot'),
      LANDING_HOW_KICKER: t('landing.how.kicker'),
      LANDING_HOW_TITLE: t('landing.how.title'),
      LANDING_HOW_LEAD: t('landing.how.lead'),
      LANDING_HOW_GUARD: t('landing.how.guard'),
      LANDING_HOW_ROLES: t('landing.how.roles'),
      LANDING_LEARN_KICKER: t('landing.learn.kicker'),
      LANDING_LEARN_TITLE: t('landing.learn.title'),
      LANDING_LEARN_LEAD: t('landing.learn.lead'),
      LANDING_LEARN_MORE: t('landing.learn.more'),
      LANDING_LEARN_GLOSSARY_TITLE: t('landing.learn.glossary.title'),
      LANDING_LEARN_GLOSSARY_BODY: t('landing.learn.glossary.body'),
      LANDING_LEARN_GLOSSARY_CTA: t('landing.learn.glossary.cta'),
      LANDING_LEARN_HELP_TITLE: t('landing.learn.help.title'),
      LANDING_LEARN_HELP_BODY: t('landing.learn.help.body'),
      LANDING_LEARN_HELP_CTA: t('landing.learn.help.cta'),
      LANDING_LEARN_TUTORIAL_TITLE: t('landing.learn.tutorial.title'),
      LANDING_LEARN_TUTORIAL_BODY: t('landing.learn.tutorial.body'),
      LANDING_LEARN_TUTORIAL_CTA: t('landing.learn.tutorial.cta'),
      HERO_FLOW_EYEBROW: t('hero.flow.eyebrow'),
      HERO_FLOW_RESULT_LABEL: t('hero.flow.resultLabel'),
      HERO_FLOW_WINDOW_PATH: t('hero.flow.windowPath'),
      HERO_FLOW_STAGES: [
        { id: 'in', label: t('hero.flow.stage.in') },
        { id: 'process', label: t('hero.flow.stage.process') },
        { id: 'gate', label: t('hero.flow.stage.gate') },
        { id: 'out', label: t('hero.flow.stage.out') },
      ] as const,
      HERO_FLOW_SCENARIOS: (['treasury', 'audit', 'escrow', 'citizen'] as const).map((id) => ({
        id,
        who: t(`hero.flow.${id}.who` as MessageKey),
        can: t(`hero.flow.${id}.can` as MessageKey),
        canvasTitle: t(`hero.flow.${id}.canvas` as MessageKey),
        result: t(`hero.flow.${id}.result` as MessageKey),
        nodes: ([1, 2, 3, 4] as const).map((n) => ({
          phase: t(`hero.flow.${id}.n${n}.phase` as MessageKey),
          title: t(`hero.flow.${id}.n${n}.title` as MessageKey),
          detail: t(`hero.flow.${id}.n${n}.detail` as MessageKey),
        })),
      })),
      HERO_CTA_STAGE_TITLE: t('hero.cta.stage.title'),
      HERO_CTA_STAGE_LEAD: t('hero.cta.stage.lead'),
      HERO_CTA_STAGE_KICKER: t('hero.cta.stage.kicker'),
      HERO_ROUTE_WHY_KICKER: t('route.why.kicker'),
      HERO_ROUTE_WHY: t('route.why'),
      HERO_ROUTE_TITLE: t('route.title'),
      HERO_ROUTE_LEAD: t('route.lead'),
      HERO_ROUTE_STEPS: ROUTE_STEP_IDS.map((id) => ({
        id,
        label: t(`route.step.${id}.label` as MessageKey),
        hint: t(`route.step.${id}.hint` as MessageKey),
        path:
          id === 'os'
            ? '/institucional'
            : id === 'catalog'
              ? '/modelos'
              : id === 'pilot'
                ? INSTITUTION_ROUTES.register
                : INSTITUTION_ROUTES.pilot,
        detail: t(`route.step.${id}.detail` as MessageKey),
        stat: t(`route.step.${id}.stat` as MessageKey),
      })),
      HERO_FIRST_MODEL: {
        kicker: t('model.first.kicker'),
        name: t('model.first.name'),
        subtitle: t('model.first.subtitle'),
        description: t('model.first.description'),
        demoLabel: t('model.first.demo'),
        path: '/modelos/egs',
        demoPath: INSTITUTION_ROUTES.desk,
      },
      HERO_GOVERNANCE_COMPARE: {
        kicker: t('compare.kicker'),
        title: t('compare.title'),
        lead: t('compare.lead'),
        traditionalLabel: t('compare.traditional'),
        governance2Label: t('compare.governance2'),
        cta: t('compare.cta'),
        ctaPath: '/modelos/egs',
        dimensions: COMPARE_DIM_IDS.map((id) => ({
          id,
          label: t(`compare.dim.${id}` as MessageKey),
          traditional: t(`compare.dim.${id}.traditional` as MessageKey),
          governance2: t(`compare.dim.${id}.g2` as MessageKey),
        })),
      },
      LANDING_MODELS_KICKER: t('landing.models.kicker'),
      LANDING_MODELS_TITLE: t('landing.models.title'),
      LANDING_MODELS_BODY: t('landing.models.body'),
      LANDING_CONSOLE_KICKER: t('landing.console.kicker'),
      LANDING_CONSOLE_TITLE: t('landing.console.title'),
      LANDING_CONSOLE_LEAD: t('landing.console.lead'),
      LANDING_WHY_KICKER: t('landing.why.kicker'),
      LANDING_WHY_TITLE: t('landing.why.title'),
      LANDING_WHY_LEAD: t('landing.why.lead'),
      LANDING_WHY_FOOT: t('landing.why.foot'),
      LANDING_WHY_ITEMS: [
        { id: 'government', title: t('landing.why.state.title'), body: t('landing.why.state.body') },
        { id: 'business', title: t('landing.why.business.title'), body: t('landing.why.business.body') },
        { id: 'citizen', title: t('landing.why.citizen.title'), body: t('landing.why.citizen.body') },
        { id: 'security', title: t('landing.why.security.title'), body: t('landing.why.security.body') },
      ] as const,
      LANDING_SERVICES_KICKER: t('landing.services.kicker'),
      LANDING_SERVICES_TITLE: t('landing.services.title'),
      LANDING_SERVICES_LEAD: t('landing.services.lead'),
      LANDING_SERVICES_ITEMS: [
        { id: 'baseline', title: t('landing.services.baseline.title'), body: t('landing.services.baseline.body') },
        { id: 'escrow', title: t('landing.services.escrow.title'), body: t('landing.services.escrow.body') },
        { id: 'sentinel', title: t('landing.services.sentinel.title'), body: t('landing.services.sentinel.body') },
        { id: 'ledger', title: t('landing.services.ledger.title'), body: t('landing.services.ledger.body') },
      ] as const,
      LANDING_SECURITY_KICKER: t('landing.security.kicker'),
      LANDING_SECURITY_TITLE: t('landing.security.title'),
      LANDING_SECURITY_LEAD: t('landing.security.lead'),
      LANDING_SECURITY_CTA: t('landing.security.cta'),
      LANDING_SECURITY_ITEMS: [
        { id: 'ed25519', title: t('landing.security.ed25519.title'), body: t('landing.security.ed25519.body') },
        { id: 'centinela', title: t('landing.security.freeze.title'), body: t('landing.security.freeze.body') },
        { id: 'trail', title: t('landing.security.trail.title'), body: t('landing.security.trail.body') },
        { id: 'pqc', title: t('landing.security.pqc.title'), body: t('landing.security.pqc.body') },
      ] as const,
      LANDING_APPLICATION_KICKER: t('landing.application.kicker'),
      LANDING_APPLICATION_TITLE: t('landing.application.title'),
      LANDING_APPLICATION_LEAD: t('landing.application.lead'),
      LANDING_APPLICATION_ITEMS: [
        {
          id: 'treasury',
          title: t('landing.application.treasury.title'),
          body: t('landing.application.treasury.body'),
          outcome: t('landing.application.treasury.outcome'),
        },
        {
          id: 'audit',
          title: t('landing.application.audit.title'),
          body: t('landing.application.audit.body'),
          outcome: t('landing.application.audit.outcome'),
        },
        {
          id: 'procurement',
          title: t('landing.application.procurement.title'),
          body: t('landing.application.procurement.body'),
          outcome: t('landing.application.procurement.outcome'),
        },
      ] as const,
      LANDING_DEVELOPERS_KICKER: t('landing.developers.kicker'),
      LANDING_DEVELOPERS_TITLE: t('landing.developers.title'),
      LANDING_DEVELOPERS_LEAD: t('landing.developers.lead'),
      LANDING_DEVELOPERS_REPO: t('landing.developers.repo'),
      LANDING_DEVELOPERS_CTA: t('landing.developers.cta'),
      LANDING_DEVELOPERS_FORK: t('landing.developers.fork'),
      LANDING_DEVELOPERS_ORG: t('landing.developers.org'),
      LANDING_CONTACT_KICKER: t('landing.contact.kicker'),
      LANDING_CONTACT_TITLE: t('landing.contact.title'),
      LANDING_CONTACT_LEAD: t('landing.contact.lead'),
      LANDING_CONTACT_SANDBOX_KICKER: t('landing.contact.sandboxKicker'),
      LANDING_CONTACT_SANDBOX_TITLE: t('landing.contact.sandboxTitle'),
      LANDING_CONTACT_SANDBOX_BODY: t('landing.contact.sandboxBody'),
      LANDING_CONTACT_SANDBOX: t('landing.contact.sandbox'),
      LANDING_CONTACT_LOGIN: t('landing.contact.login'),
      LANDING_CONTACT_TALK_KICKER: t('landing.contact.talkKicker'),
      LANDING_CONTACT_TALK_TITLE: t('landing.contact.talkTitle'),
      LANDING_CONTACT_TALK_BODY: t('landing.contact.talkBody'),
      LANDING_CONTACT_TALK: t('landing.contact.talk'),
      LANDING_CONTACT_HUB: t('landing.contact.hub'),
      LANDING_CONTACT_CONCIERGE: t('landing.contact.talk'),
      LANDING_CONTACT_REGISTER: t('landing.contact.sandbox'),
      LANDING_CONTACT_EMAIL: t('landing.contact.email'),
      LANDING_FLOW_KICKER: t('landing.flow.kicker'),
      LANDING_FLOW_TITLE: t('landing.flow.title'),
      LANDING_FLOW_LEAD: t('landing.flow.lead'),
      LANDING_CONNECT_KICKER: t('landing.connect.kicker'),
      LANDING_CONNECT_TITLE: t('landing.connect.title'),
      LANDING_CONNECT_LEAD: t('landing.connect.lead'),
      LANDING_CONNECT_CTA: t('landing.connect.cta'),
      LANDING_CONNECT_STEPS: [
        { id: 'register', title: t('landing.connect.step1.title'), body: t('landing.connect.step1.body') },
        { id: 'baseline', title: t('landing.connect.step2.title'), body: t('landing.connect.step2.body') },
        { id: 'console', title: t('landing.connect.step3.title'), body: t('landing.connect.step3.body') },
      ] as const,
      LANDING_CTA_TITLE: t('landing.cta.title'),
      LANDING_CTA_LEAD: t('landing.cta.lead'),
      LANDING_CTA_MICRO: t('landing.cta.micro'),
      LANDING_CTA_ACTION: t('landing.cta.action'),
      LANDING_CTA_CONTACT: t('landing.cta.contact'),
      LANDING_CTA_SEE_CONSOLE: t('landing.cta.seeConsole'),
      LANDING_MODELS_CATALOG: t('landing.models.catalog'),
      LANDING_PROCESS_KICKER: t('landing.process.kicker'),
      LANDING_PROCESS_TITLE: t('landing.process.title'),
      LANDING_PROCESS_LEAD: t('landing.process.lead'),
      LANDING_PROCESS_CLOUD: t('landing.process.where.cloud'),
      LANDING_PROCESS_LOCAL: t('landing.process.where.local'),
      LANDING_PROCESS_CLOUD_SHORT: t('landing.process.where.cloudShort'),
      LANDING_PROCESS_LOCAL_SHORT: t('landing.process.where.localShort'),
      LANDING_PROCESS_WHERE_LABEL: t('landing.process.where.label'),
      LANDING_PROCESS_CTA: t('landing.process.cta'),
      LANDING_PROCESS_CTA_MICRO: t('landing.process.ctaMicro'),
      LANDING_PROCESS_NEXT_DEPLOY: t('landing.process.nextDeploy'),
      LANDING_PROCESS_STEPS: [
        { id: 'build', title: t('landing.process.build.title'), body: t('landing.process.build.body') },
        { id: 'where', title: t('landing.process.where.title'), body: t('landing.process.where.body') },
        {
          id: 'configure',
          title: t('landing.process.configure.title'),
          body: t('landing.process.configure.body'),
        },
      ] as const,
      LANDING_DEPLOY_KICKER: t('landing.deploy.kicker'),
      LANDING_DEPLOY_TITLE: t('landing.deploy.title'),
      LANDING_DEPLOY_LEAD: t('landing.deploy.lead'),
      LANDING_DEPLOY_WHERE_LABEL: t('landing.deploy.where.label'),
      LANDING_DEPLOY_CLOUD: t('landing.deploy.cloud'),
      LANDING_DEPLOY_LOCAL: t('landing.deploy.local'),
      LANDING_DEPLOY_CTA: t('landing.deploy.cta'),
      LANDING_DEPLOY_CTA_MICRO: t('landing.deploy.ctaMicro'),
      LANDING_DEPLOY_BACK_BUILD: t('landing.deploy.backBuild'),
      LANDING_DEPLOY_SEE_RESULTS: t('landing.deploy.seeResults'),
      LANDING_DEPLOY_POINTS: [
        { id: 'publish', title: t('landing.deploy.point1.title'), body: t('landing.deploy.point1.body') },
        { id: 'guard', title: t('landing.deploy.point2.title'), body: t('landing.deploy.point2.body') },
        { id: 'defend', title: t('landing.deploy.point3.title'), body: t('landing.deploy.point3.body') },
      ] as const,
      LANDING_CHALLENGE_KICKER: t('landing.models.kicker'),
      LANDING_CHALLENGE_TITLE: t('landing.models.title'),
      LANDING_CHALLENGE_LEAD: t('landing.models.body'),
      LANDING_CHALLENGE_BODY: '',
      HERO_PIPELINE_STEPS: PIPELINE_STEP_IDS.map((id) => ({
        id,
        label: t(`pipeline.step.${id}` as MessageKey),
      })),
      HERO_PIPELINE_CAPTION: t('pipeline.caption'),
      HERO_PIPELINE_KICKER: t('pipeline.kicker'),
      demoProgramName: t(programKey),
    };
  }, [t, sovereign.iso, sovereign.jurisdictionCode]);
}
